#!/bin/bash
clear

criarAdmin(){
    clear
    php bin/criarAdmin.php
    echo "pronto"
}

migrarTabelas() {
    clear
    echo "migrando as tabelas..."
    php bin/migrarTabelas.php
    echo "pronto"
}

echo "Digite a opção:"
echo "1) migrar tabelas"
echo "2) criar conta de administrador"
printf "Opção número "
read opt

case $opt
in
    1) migrarTabelas ;;
    2) criarAdmin ;;
    *) echo "opção inválida" ;;
esac
